# -*- encoding : utf-8 -*-
# Read about factories at http://github.com/thoughtbot/factory_girl

Factory.define :estagiario do |f|
  f.matricula "MyString"
  f.matricula_grh "MyString"
  f.tempo_em_curso "MyString"
  f.formato_tempo_em_curso "MyString"
  f.situacao_da_matricula "MyString"
  f.escolaridade "MyString"
  f.nome "MyString"
  f.data_de_nascimento "2011-03-25"
  f.cpf "13157288776"
  f.rg "MyString"
  f.orgao_expedidor "MyString"
  f.data_de_expedicao "2011-03-25"
  f.nacionalidade "MyString"
  f.naturalidade "MyString"
  f.sexo "MyString"
  f.filiacao "MyString"
  f.estado_civil "MyString"
  f.nome_do_conjuge "MyString"
  f.certificado_de_reservista "MyString"
  f.titulo_de_eleitor "MyString"
  f.cep "MyString"
  f.estado "MyString"
  f.cidade "MyString"
  f.bairro "MyString"
  f.rua "MyString"
  f.numero "MyString"
  f.complemento "MyString"
  f.telefone "MyString"
  f.celular "MyString"
  f.email "email@email.com"
end

